# Generated by Django 4.1.5 on 2023-02-02 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAnswers',
            fields=[
                ('username', models.CharField(max_length=64, verbose_name='username')),
                ('answer', models.CharField(max_length=64, verbose_name='username')),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='questionId')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024, verbose_name='question')),
            ],
        ),
        migrations.CreateModel(
            name='TANs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authenticated', models.BooleanField(default=0, verbose_name='authenticated')),
                ('tan', models.CharField(max_length=128, verbose_name='TAN')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Please enter within 6 letters', max_length=6, unique=True, verbose_name='username')),
                ('password', models.CharField(help_text='Please enter at least 6 characters', max_length=64, verbose_name='password')),
                ('tan', models.IntegerField(help_text='Please enter at least 6 characters', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='TAN')),
            ],
        ),
    ]
