# Generated by Django 4.1.5 on 2023-01-31 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAnswers',
            fields=[
                ('username', models.CharField(max_length=64, verbose_name='user_name')),
                ('answer', models.CharField(max_length=64, verbose_name='user_name')),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='questionId')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQuestions',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='questionId')),
                ('question', models.CharField(max_length=128, verbose_name='user_name')),
            ],
        ),
        migrations.CreateModel(
            name='TANs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authenticated', models.BooleanField(default=0, verbose_name='authenticated')),
                ('tan', models.CharField(max_length=128, verbose_name='TAN')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='user_name')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('tan', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='TANv')),
            ],
        ),
    ]
