# Generated by Django 4.1.5 on 2023-02-04 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='please select a security question', max_length=1024, verbose_name='question')),
            ],
        ),
        migrations.CreateModel(
            name='TANs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tan', models.CharField(default='None', help_text='Please enter 3 characters', max_length=6, verbose_name='TAN')),
                ('authenticated', models.BooleanField(default=0, verbose_name='authenticated')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Please enter within 6 letters', max_length=6, unique=True, verbose_name='username')),
                ('password', models.CharField(help_text='Please enter at least 6 characters', max_length=64, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=64, verbose_name='username')),
                ('question_id', models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, to='user.securityquestions', verbose_name='question id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users', verbose_name='user id')),
            ],
        ),
    ]
