# Generated by Django 4.1.5 on 2023-02-02 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityanswers',
            name='answer',
            field=models.CharField(max_length=64, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='securityanswers',
            name='username',
            field=models.CharField(max_length=64, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='securityquestions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='securityquestions',
            name='question',
            field=models.CharField(max_length=1024, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(help_text='Please enter at least 6 characters', max_length=64, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tan',
            field=models.IntegerField(help_text='Please enter at least 6 characters', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='TAN'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(help_text='Please enter within 6 letters', max_length=6, unique=True, verbose_name='username'),
        ),
    ]
