# Generated by Django 4.1.5 on 2023-02-04 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityquestions',
            name='question',
            field=models.CharField(help_text='please select a security question', max_length=1024, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='tans',
            name='tan',
            field=models.IntegerField(help_text='Please enter 3 characters', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='TAN'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tan',
            field=models.ForeignKey(help_text='Please enter 3 characters', on_delete=django.db.models.deletion.CASCADE, to='user.tans', verbose_name='TAN'),
        ),
    ]
